### PR TITLE
Move module directory; add unit test code; setup files; update README

### PR DESCRIPTION
**Pull request by drphilmarshall**
Looks good at first glance, but let's get travis CI on the case.

### CODE REVIEW

**Comment by drphilmarshall** [comment]
OK @jchiang87 , Travis CI is now set up. Can you please merge from master and edit `.travis.yml` so that it runs your tests? I got the setup help from [this cookbook](https://docs.travis-ci.com/user/languages/python).

**Comment by drphilmarshall** [comment]
Hey! We haven't finished your code review yet!

**Comment by drphilmarshall** [comment]
Although I admit that your build is passing :-) Thanks very much Jim, this was a good exercise.

**Comment by jchiang87** [comment]
Sorry! I misread the "from master" as "into master".

**Comment by tony-johnson** [comment]
At some point we should probably discuss the pros/cons of jenkins vs 
travis ci vs both.

Tony

**Comment by drphilmarshall** [comment]
Yep - GitHub makes travis CI easy, so we just went with that for now. It'll
choke on anything that depends on the stack though, I expect.

**Pull request merged**
