### PR TITLE
PEP8 style

### PR DESCRIPTION
**Pull request by drphilmarshall**
For my own edification, I tried to make `monitor.py` pass my `pylint` linter. See teh "Changed Files": this is about as far as I could get. The main thing was that we had mixedCase variables everywhere - is that a DM standard?

### CODE REVIEW

**Comment by rbiswas4** [comment]
There is a standard that attribute names should be CamelCase with a leading lower case. But I am not sure about temporary variables. 

http://developer.lsst.io/en/latest/coding/python_style_guide.html#naming-conventions

**Comment by brianv0** [comment]
It's in the original style guide, but it's almost effectively deprecated:

https://jira.lsstcorp.org/browse/RFC-81
https://jira.lsstcorp.org/browse/RFC-97

Since C++ doesn't enforce a de-facto style the same way Python (or java) does, it was agreed that effectively adopting PEP8 for C++ stack projects (using underscores for functions_and_variables, CamelCase for classes) is the way forward, but it wasn't decided on exactly how that should happen. Because the amount of legacy code, they want to approach this change with "baby steps".

Note: PEP8 allows camelCase methods and variables but it encourages underscores.

**Comment by drphilmarshall** [comment]
OK, thanks! I vote we merge this PR but I leave it to you, @jbkalmbach
My main motivation is to get my linter to shut up :-)

On Wed, Mar 2, 2016 at 1:58 PM, Brian Van Klaveren <notifications@github.com

**Comment by jchiang87** [comment]
Hey @drphilmarshall,

You can silence warnings selectively via your .pylintrc file:

```
$ cat ~/.pylintrc
[MESSAGES CONTROL]
disable=C0103
```

Depending on your version of pylint, it might be `disable_msgs` instead.
See http://pylint-messages.wikidot.com/all-codes

**Comment by drphilmarshall** [comment]
Aha! This is where we would write a DESC pylint configuration, perhaps in
an "Environment" module...

**Comment by jbkalmbach** [comment]
I agree Phil that we should try to use linters to make our code better! Merged!

**Comment by rbiswas4** [comment]
There is also a pep8 converter:

https://pypi.python.org/pypi/autopep8

that converts to pep8 style code that does not conform to it.

**Pull request merged**
