### PR TITLE
Update setup_jupyter-dev.md

### PR DESCRIPTION
**Pull request by jbkalmbach**
Added introduction to jupyter-dev instructions to motivate their use.

### CODE REVIEW

**Comment by jbkalmbach** [comment]
Hi @drphilmarshall, if you have some time please take a look at my updated instructions for jupyter-dev and let me know what else you'd like to see.

**Comment by danielsf** [comment]
Cell 7 of `light_curve_example.ipynb` fails with

```

RuntimeErrorTraceback (most recent call last)
<ipython-input-7-d386c5b8a664> in <module>()
      1 obj_id = 38526
----> 2 lc.build_lightcurve_from_db(objid = obj_id)

/global/u1/d/danielsf/monitor/python/desc/monitor/monitor.pyc in build_lightcurve_from_db(self, objid, ra_dec, tol, database, host, port, driver)
    132                                  'ra,dec location.'))
    133 
--> 134         dbConn_lc = dbi(database=database, host=host, port=port, driver=driver)
    135 
    136         if objid is not None:

/global/u1/d/danielsf/monitor/python/desc/monitor/dbConnection.pyc in __init__(self, database, host, port, driver)
     10 
     11         self._dbo = DBObject(database=database, host=host, port=port,
---> 12                              driver=driver)
     13 
     14     def forcedSourceFromId(self, objectId):

/global/common/cori/contrib/lsst/lsstDM/v12_1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.pyc in __init__(self, database, driver, host, port, verbose, connection)
    272 
    273             self.connection = DBConnection(database=self.database, driver=self.driver, host=self.host,
--> 274                                            port=self.port, verbose=self.verbose)
    275         else:
    276             self.connection = connection

/global/common/cori/contrib/lsst/lsstDM/v12_1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.pyc in __init__(self, database, driver, host, port, verbose)
    111 
    112         self._validate_conn_params()
--> 113         self._connect_to_engine()
    114 
    115 

/global/common/cori/contrib/lsst/lsstDM/v12_1/Linux64/sims_catalogs/master-g89e82bbb01+1/python/lsst/sims/catalogs/db/dbConnection.pyc in _connect_to_engine(self)
    119         if self._host:
    120             try:
--> 121                 authDict = {'username': DbAuth.username(self._host, str(self._port)),
    122                             'password': DbAuth.password(self._host, str(self._port))}
    123             except:

/global/common/cori/contrib/lsst/lsstDM/v12_1/Linux64/daf_persistence/12.1/python/lsst/daf/persistence/persistenceLib.pyc in username(host, port)
   1194     def username(host, port):
   1195         """username(std::string const & host, std::string const & port) -> std::string"""
-> 1196         return _persistenceLib.DbAuth_username(host, port)
   1197 
   1198     username = staticmethod(username)

RuntimeError: 
  File "src/DbAuth.cc", line 112, in std::pair<std::basic_string<char>, std::basic_string<char> > search(const string&, const string&)
    No credentials found for host/port: 127.0.0.1:3307 {0}
lsst::pex::exceptions::RuntimeError: 'No credentials found for host/port: 127.0.0.1:3307'
```

**Comment by danielsf** [comment]
Never mind.  User error.  This looks good.

**Review by drphilmarshall — APPROVED** [review]
This is great - nice job, Bryce! I'm going to merge this, rename the file, and then point the SUIT team at it so that they know we are now working in this mode. They might offer us some widgets to play with! :-) Thanks for making this.

**Pull request merged**
