### PR TITLE
Issue#52/fix snid problem

### LINKED ISSUE #52: Changes to TwinSN table?
Hi @rbiswas4,

I'm trying to run your https://github.com/DarkEnergyScienceCollaboration/Monitor/blob/master/examples/reference_lc.ipynb notebook, but I'm getting this error for cell 14:

```
DatabaseError                             Traceback (most recent call last)
<ipython-input-14-aeb7556a9869> in <module>()
----> 1 ids = reflc.allIdinTable(chunksize=None)
      2 print(ids.astype(int).values.flatten())

/u/gl/jchiang/links/desc_projects/Monitor/python/desc/monitor/truth.pyc in allIdinTable(self, sqlconstraint, chunksize)
    272 
    273         x = pd.read_sql_query(query, con=self.dbConnection,
--> 274                               chunksize=chunksize)
    275         return x
    276 

/nfs/farm/g/desc/u1/LSST_Stack_2016-04-12/lsstsw/miniconda/lib/python2.7/site-packages/pandas/io/sql.pyc in read_sql_query(sql, con, index_col, coerce_float, params, parse_dates, chunksize)
    429     return pandas_sql.read_query(
    430         sql, index_col=index_col, params=params, coerce_float=coerce_float,
--> 431         parse_dates=parse_dates, chunksize=chunksize)
    432 
    433 

/nfs/farm/g/desc/u1/LSST_Stack_2016-04-12/lsstsw/miniconda/lib/python2.7/site-packages/pandas/io/sql.pyc in read_query(self, sql, index_col, coerce_float, params, parse_dates, chunksize)
   1597 
   1598         args = _convert_params(sql, params)
-> 1599         cursor = self.execute(*args)
   1600         columns = [col_desc[0] for col_desc in cursor.description]
   1601 

/nfs/farm/g/desc/u1/LSST_Stack_2016-04-12/lsstsw/miniconda/lib/python2.7/site-packages/pandas/io/sql.pyc in execute(self, *args, **kwargs)
   1574             ex = DatabaseError(
   1575                 "Execution failed on sql '%s': %s" % (args[0], exc))
-> 1576             raise_with_traceback(ex)
   1577 
   1578     @staticmethod

/nfs/farm/g/desc/u1/LSST_Stack_2016-04-12/lsstsw/miniconda/lib/python2.7/site-packages/pandas/io/sql.pyc in execute(self, *args, **kwargs)
   1562                 cur.execute(*args, **kwargs)
   1563             else:
-> 1564                 cur.execute(*args)
   1565             return cur
   1566         except Exception as exc:

pymssql.pyx in pymssql.Cursor.execute (pymssql.c:7483)()

DatabaseError: Execution failed on sql 'SELECT snid FROM TwinkSN': (207, "Invalid column name 'snid'.DB-Lib error message 207, severity 16:\nGeneral SQL Server error: Check messages from the SQL Server\n")
```

Has there been a change to that table?

### PR DESCRIPTION
**Pull request by rbiswas4**
- Changed import of `DBObject` in dbConnection to reflect changes to catsim architecture
- Changed `snid` to `id` in `truth.py` to reflect changes to catsim database table variable names
- Changed `snid` to `id` and fixed `DBObject` import  in example notebook.

Notebook works on my computer.

Fixes #52

### CODE REVIEW

**Comment by jchiang87** [comment]
@rbiswas4 These changes look fine, but they are breaking in travis since the distribution of lsst-sims we are getting from `http://conda.lsst.codes/sims` doesn't seem to have the `lsst.sims.catalogs.db` module yet.  Is that available from a conda dist?  @danielsf Have we settled on a sims build to use? (https://github.com/DarkEnergyScienceCollaboration/Twinkles/issues/306) We'll also need to install that at SLAC and NERSC to make progress on Run3.

**Comment by rbiswas4** [comment]
Right,  the thing is that catsim has changed so that `lsst.sims.catalogs.generation` is now `lsst.sims.catalogs`. But it seems that this is not reflected in the conda version yet. I was going to check with @danielsf if this is really the case. 

The unfortunate problem is this might be hard to handle with something like a `skip test`  condition

**Comment by danielsf** [comment]
Sorry.  Still no conda build of sims 2.3.0.  I will ping the appropriate players.

**Comment by jchiang87** [comment]
I've got things set up in the SLAC Jenkins server to build against our installation of sims 2.3.1.   Unless I hear some objections before 4pm PT, I'll merge this into master so that we can run in Jenkins.  (I still need to figure out how to get it to trigger on PRs, etc.).

**Comment by jchiang87** [comment]
BTW, the Jenkins builds are [here](http://srs.slac.stanford.edu/hudson/view/LSST/job/Monitor/)

**Pull request merged**
