### PR TITLE
Prevent variable leaks

### LINKED ISSUE #34: Prevent the leakage of imports into namespace
Currently, modules in the monitor package import several packages without defining an `__all__`, and then use a `from module import *` style. This causes a leakage of all imported package names into the monitor namespace. We need to change this.

### PR DESCRIPTION
**Pull request by rbiswas4**
Added an **all** variable to prevent leakage of imports into the Monitor Namespace. This should fix #34

### CODE REVIEW

**Comment by jchiang87** [comment]
I updated the `__all__` variables, so that all of the desired components are imported from each module.  I think we should get rid of the `Monitor` class (and its tests) since it's currently just the boilerplate example code that the package was created with.  Or maybe we should figure out what that `Monitor` class is supposed to do and implement it.  @rbiswas4 @drphilmarshall @jbkalmbach Thoughts?

**Comment by rbiswas4** [comment]
@jchiang87 Thanks for fixing the functions I had missed out. I think @drphilmarshall put in the Monitor as example code. Maybe we should move it to docs if it is not really performing any function?

In the meantime, trying to put in the `__all__` variable I realized that some code that I had on my computer had never been committed and hence never been seen by anyone. In fact when I was talking about outputing the reference light curves to the `LightCurve` class, last week this is what I thinking about.

The basic idea of the this class is supposed to be that once you populate the light curve (whether it is from reference truths, from a data repository or from old data, it should be able to do all the possible computations/transformations  you might want to do.

**Comment by drphilmarshall** [comment]
That's right. If you want to monitor objects, you need a Monitor Object to
do it for you! See my previous email on the python lines I had imagined us
wanting to write. Feel free to go ahead and remove the monitor class for
now - but if we start proliferating scripts that do various things with
ensembles of objects and their light curves, we might want to resurrect the
notion.

**Comment by rbiswas4** [comment]
I think it will be there eventually be in when we have a piece of code that will return a list of possible sources for an objectID given search parameters including [].

**Comment by rbiswas4** [comment]
OK. Unless anyone has any objections, I will merge this branch. 

BTW, since there were conflicts I rebased but had to force push. Is there a preference for this vs merging to master on the terminal?

**Pull request merged**
